### ISSUE TITLE
html minification not working for templates

### ISSUE THREAD

**Issue by soumak77** [base-apps/angular-base-apps-template#1]
The way in which `base-apps-router` is integrated into the brunch build causes the html files to not be minified when run in production mode.  The problem is that the minify phase is run before the `onCompile` hook used in brunch, so the files run through `base-apps-router` are overwriting the minified html files.

The build should be updated so that the `base-apps-router` is run as part of the `preCompile` hook.  The html files can be output to the `public` folder and the asset matching can be updated to exclude those html files so that they do not overwrite the files in the `public` folder.

While this is being addressed, the `routes.js` file outputted by the router should be configured to be included inside the compiled `app.js` file.  It'll have to be included after the `dynamicRouting` source.

All this is building up to needing a dedicated brunch plugin to integrate `base-apps-router` cleanly.

**Comment by soumak77** [comment]
@tolyo since you have more experience with brunch, could you look into this?  I tried to figure it out but I'm not sure there is a way to do it properly without creating a brunch plugin.

**Comment by tolyo** [comment]
@soumak77  I think something like a custom build script might do.

**Comment by soumak77** [comment]
@tolyo would you be able to update [html-pages-brunch](https://github.com/tolyo/html-pages-brunch) to add a setting to keep the front matter in the html file?  This would allow `base-apps-router` to run on the processed html and once it removes the front matter, the resulting file will be fully minified.

This would be a generic way to make it possible to use `base-apps-router` with `html-pages-brunch`, though if you want to provide even further integration of the two modules that would be nice as well.

**Comment by soumak77** [comment]
@tolyo the integration has been simplified with https://github.com/tolyo/html-pages-brunch/pull/9.  I've updated the firebase template to work with the new settings.  It'll create a config-routes.js file during the preCompile hook which is imported into app.js after the dynamic routing modules.  The front matter is removed by `html-pages-brunch` instead of `base-apps-router` during the compile phase.

**Comment by tolyo** [comment]
@soumak77 Fixed
