### ISSUE TITLE
Unknown HashMapProvider

### ISSUE THREAD

**Issue by markusgraube** [base-apps/angular-base-apps-template#8]
When following the guidelines for installing I get the following error in Javascript after opening `http://localhost:3333`

```
Uncaught Error: [$injector:unpr] Unknown provider: $$HashMapProvider <- $$HashMap <- $$animateQueue <- $animate <- $compile <- $$animateQueue
http://errors.angularjs.org/1.6.4/$injector/unpr?p0=%24%24HashMapProvider%2…eQueue%20%3C-%20%24animate%20%3C-%20%24compile%20%3C-%20%24%24animateQueue
    at vendor.js:46066
    at vendor.js:50789
    at Object.getService [as get] (vendor.js:50944)
    at vendor.js:50794
    at getService (vendor.js:50944)
    at injectionArgs (vendor.js:50969)
    at Object.invoke (vendor.js:50995)
    at vendor.js:50795
    at getService (vendor.js:50944)
    at injectionArgs (vendor.js:50969)
```

**Comment by soumak77** [comment]
I believe this is related to #5.

I just published a [new version](https://github.com/base-apps/angular-base-apps/releases/tag/v2.0.10) of angular-base-apps which adds support for angular 1.6.x.  Give that a try and let me know if it fixes your issues.

**Comment by thebrownfox** [comment]
@markusgraube just run` npm update` and/or delete line `import angular from 'angular';` in app.js.

**Comment by markusgraube** [comment]
Thank you!
`npm update` has solved it now.
